#Spigot related
name: HopeCommander-Spigot
main: me.hopedev.hopecommander.Spigot.SpigotMain
version: 1.2.7
description: A Bridge between spigot and bungee, one way only
author: HopeDev
commands:
  hopecommander:
    description: Main Command for HopeCommander
    permission: hc.command